In [46]:
import numpy as np
from NeuralNetwork import LinearLayer,Sequential,SigmoidLayer,TanhLayer,SoftmaxLayer

In [47]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

In [48]:
# Using all sigmoid layers
model = Sequential()
model.add(LinearLayer(2, 2))
model.add(SigmoidLayer())
model.add(LinearLayer(2, 4))
model.add(SigmoidLayer())
model.add(LinearLayer(4, 1))
model.add(SigmoidLayer())


model.train(X,y,learning_rate=0.05,patience=5,loss_print_count = 1000,epochs=100000)
output = model.predict(X)

print("Predictions:")
binary_outputs = np.where(output >= 0.5, 1, 0)
print(binary_outputs)


Epoch 99000/100000: loss = 0.0006467395383082056
Predictions:
[[0]
 [1]
 [1]
 [0]]


In [49]:
# using tanh 
model = Sequential()
model.add(LinearLayer(2, 2))
model.add(TanhLayer())
model.add(LinearLayer(2, 4))
model.add(TanhLayer())
model.add(LinearLayer(4, 1))
model.add(SigmoidLayer())
model.train(X,y,learning_rate=0.01,patience=5,epochs=10000)

# evaluate the trained model
output = model.predict(X)

print("Predictions:")
binary_outputs = np.where(output >= 0.5, 1, 0)
print(binary_outputs)


Epoch 9999/10000: loss = 0.026910218605623683
Predictions:
[[0]
 [1]
 [1]
 [0]]


Thus with tanh , even with a smaller learning rate and less number of epochs, the model was able to converge and give better predictions. 


In [50]:
model.save_weights("XOR_solved.w")

In [56]:
model.load_weights("XOR_solved.w.npy")

In [57]:
model.predict(X)
print("Predictions:")
binary_outputs = np.where(output >= 0.5, 1, 0)
print(binary_outputs)


Predictions:
[[0]
 [1]
 [1]
 [0]]
